// Auto-generated by LibreLane
module chip_top_full(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input clk_int,
  input rst_n,
  input scan_in,
  input scan_shift,
  input scan_load,
  input scan_i0o1,
  output scan_out,
  output[4:0] gpio_out,
  input[1:0] gpio_in,
  output uart_tx,
  input uart_rx,
  output spi_sclk,
  output spi_mosi,
  output spi_cs_n
);
endmodule
