/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* blackbox =  1  *)
(* dynports =  1  *)
(* top =  1  *)
(* src = "openlane/ibex_top/ibex_top.flat.v:12559.1-13401.10" *)
module ibex_top(clk_i, rst_ni, test_en_i, ram_cfg_icache_tag_i, ram_cfg_icache_tag_o, ram_cfg_icache_data_i, ram_cfg_icache_data_o, hart_id_i, boot_addr_i, instr_req_o, instr_gnt_i, instr_rvalid_i, instr_addr_o, instr_rdata_i, instr_rdata_intg_i, instr_err_i, data_req_o, data_gnt_i, data_rvalid_i, data_we_o, data_be_o
, data_addr_o, data_wdata_o, data_wdata_intg_o, data_rdata_i, data_rdata_intg_i, data_err_i, irq_software_i, irq_timer_i, irq_external_i, irq_fast_i, irq_nm_i, scramble_key_valid_i, scramble_key_i, scramble_nonce_i, scramble_req_o, debug_req_i, crash_dump_o, double_fault_seen_o, fetch_enable_i, mcounteren_writable_i, alert_minor_o
, alert_major_internal_o, alert_major_bus_o, core_sleep_o, scan_rst_ni, lockstep_cmp_en_o, data_req_shadow_o, data_we_shadow_o, data_be_shadow_o, data_addr_shadow_o, data_wdata_shadow_o, data_wdata_intg_shadow_o, instr_req_shadow_o, instr_addr_shadow_o);
  parameter PMPEnable = 0;
  parameter MHPMCounterNum = 0;
  parameter RV32E = 0;
  parameter RV32M = 0;
  parameter RV32B = 0;
  parameter ICache = 0;
  parameter DbgTriggerEn = 0;
  parameter SecureIbex = 0;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12665.13-12665.18" *)
  input clk_i;
  wire clk_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12666.13-12666.19" *)
  input rst_ni;
  wire rst_ni;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12667.13-12667.22" *)
  input test_en_i;
  wire test_en_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12670.76-12670.96" *)
  input [23:0] ram_cfg_icache_tag_i;
  wire [23:0] ram_cfg_icache_tag_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12672.77-12672.97" *)
  output [1:0] ram_cfg_icache_tag_o;
  wire [1:0] ram_cfg_icache_tag_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12673.76-12673.97" *)
  input [23:0] ram_cfg_icache_data_i;
  wire [23:0] ram_cfg_icache_data_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12674.77-12674.98" *)
  output [1:0] ram_cfg_icache_data_o;
  wire [1:0] ram_cfg_icache_data_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12675.20-12675.29" *)
  input [31:0] hart_id_i;
  wire [31:0] hart_id_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12676.20-12676.31" *)
  input [31:0] boot_addr_i;
  wire [31:0] boot_addr_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12677.14-12677.25" *)
  output instr_req_o;
  wire instr_req_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12678.13-12678.24" *)
  input instr_gnt_i;
  wire instr_gnt_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12679.13-12679.27" *)
  input instr_rvalid_i;
  wire instr_rvalid_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12680.21-12680.33" *)
  output [31:0] instr_addr_o;
  wire [31:0] instr_addr_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12681.20-12681.33" *)
  input [31:0] instr_rdata_i;
  wire [31:0] instr_rdata_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12682.19-12682.37" *)
  input [6:0] instr_rdata_intg_i;
  wire [6:0] instr_rdata_intg_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12683.13-12683.24" *)
  input instr_err_i;
  wire instr_err_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12684.14-12684.24" *)
  output data_req_o;
  wire data_req_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12685.13-12685.23" *)
  input data_gnt_i;
  wire data_gnt_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12686.13-12686.26" *)
  input data_rvalid_i;
  wire data_rvalid_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12687.14-12687.23" *)
  output data_we_o;
  wire data_we_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12688.20-12688.29" *)
  output [3:0] data_be_o;
  wire [3:0] data_be_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12689.21-12689.32" *)
  output [31:0] data_addr_o;
  wire [31:0] data_addr_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12690.21-12690.33" *)
  output [31:0] data_wdata_o;
  wire [31:0] data_wdata_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12691.20-12691.37" *)
  output [6:0] data_wdata_intg_o;
  wire [6:0] data_wdata_intg_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12692.20-12692.32" *)
  input [31:0] data_rdata_i;
  wire [31:0] data_rdata_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12693.19-12693.36" *)
  input [6:0] data_rdata_intg_i;
  wire [6:0] data_rdata_intg_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12694.13-12694.23" *)
  input data_err_i;
  wire data_err_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12695.13-12695.27" *)
  input irq_software_i;
  wire irq_software_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12696.13-12696.24" *)
  input irq_timer_i;
  wire irq_timer_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12697.13-12697.27" *)
  input irq_external_i;
  wire irq_external_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12698.20-12698.30" *)
  input [14:0] irq_fast_i;
  wire [14:0] irq_fast_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12699.13-12699.21" *)
  input irq_nm_i;
  wire irq_nm_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12700.13-12700.33" *)
  input scramble_key_valid_i;
  wire scramble_key_valid_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12701.21-12701.35" *)
  input [127:0] scramble_key_i;
  wire [127:0] scramble_key_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12702.20-12702.36" *)
  input [63:0] scramble_nonce_i;
  wire [63:0] scramble_nonce_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12703.14-12703.28" *)
  output scramble_req_o;
  wire scramble_req_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12704.13-12704.24" *)
  input debug_req_i;
  wire debug_req_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12705.22-12705.34" *)
  output [159:0] crash_dump_o;
  wire [159:0] crash_dump_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12706.14-12706.33" *)
  output double_fault_seen_o;
  wire double_fault_seen_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12708.19-12708.33" *)
  input [3:0] fetch_enable_i;
  wire [3:0] fetch_enable_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12709.19-12709.40" *)
  input [3:0] mcounteren_writable_i;
  wire [3:0] mcounteren_writable_i;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12710.14-12710.27" *)
  output alert_minor_o;
  wire alert_minor_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12711.14-12711.36" *)
  output alert_major_internal_o;
  wire alert_major_internal_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12712.14-12712.31" *)
  output alert_major_bus_o;
  wire alert_major_bus_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12713.14-12713.26" *)
  output core_sleep_o;
  wire core_sleep_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12714.13-12714.24" *)
  input scan_rst_ni;
  wire scan_rst_ni;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12715.20-12715.37" *)
  output [3:0] lockstep_cmp_en_o;
  wire [3:0] lockstep_cmp_en_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12716.14-12716.31" *)
  output data_req_shadow_o;
  wire data_req_shadow_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12717.14-12717.30" *)
  output data_we_shadow_o;
  wire data_we_shadow_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12718.20-12718.36" *)
  output [3:0] data_be_shadow_o;
  wire [3:0] data_be_shadow_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12719.21-12719.39" *)
  output [31:0] data_addr_shadow_o;
  wire [31:0] data_addr_shadow_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12720.21-12720.40" *)
  output [31:0] data_wdata_shadow_o;
  wire [31:0] data_wdata_shadow_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12721.20-12721.44" *)
  output [6:0] data_wdata_intg_shadow_o;
  wire [6:0] data_wdata_intg_shadow_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12722.14-12722.32" *)
  output instr_req_shadow_o;
  wire instr_req_shadow_o;
  (* src = "openlane/ibex_top/ibex_top.flat.v:12723.21-12723.40" *)
  output [31:0] instr_addr_shadow_o;
  wire [31:0] instr_addr_shadow_o;
endmodule
