/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module gpio(clk, rst_n, sel, we, wdata, rdata, gpio_out, gpio_in);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input sel;
  wire sel;
  input we;
  wire we;
  input [31:0] wdata;
  wire [31:0] wdata;
  output [31:0] rdata;
  wire [31:0] rdata;
  output [7:0] gpio_out;
  wire [7:0] gpio_out;
  input [7:0] gpio_in;
  wire [7:0] gpio_in;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire [7:0] out_reg;
  wire [7:0] sync1;
  wire [7:0] sync2;
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _09_ (
    .A1(sel),
    .A2(we),
    .ZN(_08_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _10_ (
    .I0(wdata[6]),
    .I1(out_reg[6]),
    .S(_08_),
    .Z(_00_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _11_ (
    .I0(wdata[5]),
    .I1(out_reg[5]),
    .S(_08_),
    .Z(_01_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _12_ (
    .I0(wdata[4]),
    .I1(out_reg[4]),
    .S(_08_),
    .Z(_02_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _13_ (
    .I0(wdata[3]),
    .I1(out_reg[3]),
    .S(_08_),
    .Z(_03_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _14_ (
    .I0(wdata[2]),
    .I1(out_reg[2]),
    .S(_08_),
    .Z(_04_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _15_ (
    .I0(wdata[1]),
    .I1(out_reg[1]),
    .S(_08_),
    .Z(_05_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _16_ (
    .I0(wdata[0]),
    .I1(out_reg[0]),
    .S(_08_),
    .Z(_06_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _17_ (
    .I0(wdata[7]),
    .I1(out_reg[7]),
    .S(_08_),
    .Z(_07_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _18_ (
    .CLK(clk),
    .D(_05_),
    .Q(out_reg[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _19_ (
    .CLK(clk),
    .D(_04_),
    .Q(out_reg[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _20_ (
    .CLK(clk),
    .D(_03_),
    .Q(out_reg[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _21_ (
    .CLK(clk),
    .D(_02_),
    .Q(out_reg[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _22_ (
    .CLK(clk),
    .D(_01_),
    .Q(out_reg[5]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _23_ (
    .CLK(clk),
    .D(_00_),
    .Q(out_reg[6]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _24_ (
    .CLK(clk),
    .D(_07_),
    .Q(out_reg[7]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _25_ (
    .CLK(clk),
    .D(gpio_in[0]),
    .Q(sync1[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _26_ (
    .CLK(clk),
    .D(gpio_in[1]),
    .Q(sync1[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _27_ (
    .CLK(clk),
    .D(gpio_in[2]),
    .Q(sync1[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _28_ (
    .CLK(clk),
    .D(gpio_in[3]),
    .Q(sync1[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _29_ (
    .CLK(clk),
    .D(gpio_in[4]),
    .Q(sync1[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _30_ (
    .CLK(clk),
    .D(gpio_in[5]),
    .Q(sync1[5]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _31_ (
    .CLK(clk),
    .D(gpio_in[6]),
    .Q(sync1[6]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _32_ (
    .CLK(clk),
    .D(gpio_in[7]),
    .Q(sync1[7]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _33_ (
    .CLK(clk),
    .D(sync1[0]),
    .Q(sync2[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _34_ (
    .CLK(clk),
    .D(sync1[1]),
    .Q(sync2[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _35_ (
    .CLK(clk),
    .D(sync1[2]),
    .Q(sync2[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _36_ (
    .CLK(clk),
    .D(sync1[3]),
    .Q(sync2[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _37_ (
    .CLK(clk),
    .D(sync1[4]),
    .Q(sync2[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _38_ (
    .CLK(clk),
    .D(sync1[5]),
    .Q(sync2[5]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _39_ (
    .CLK(clk),
    .D(sync1[6]),
    .Q(sync2[6]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _40_ (
    .CLK(clk),
    .D(sync1[7]),
    .Q(sync2[7]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _41_ (
    .CLK(clk),
    .D(_06_),
    .Q(out_reg[0]),
    .RN(rst_n)
  );
  assign gpio_out = out_reg;
  assign rdata = { 24'h000000, sync2 };
endmodule
